### ISSUE TITLE
Docker mod fails on startup

### ISSUE THREAD

**Issue by ackerthehacker2** [gabe565/linuxserver-mod-vuetorrent#14]
Using your mod .. I get this error on container startup -

023-05-31 02:36:17 [mod-init] Applying gabe565/linuxserver-mod-vuetorren files to container
2023-05-31 02:40:22 [mod-init] Attempting to run Docker Modification Logic
2023-05-31 02:40:14 s6-rc: fatal: unable to take locks: No such file or directory
2023-05-31 02:40:14 s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111

My docker compose file:

services:
  qbit:
    image: linuxserver/qbittorrent:latest
    container_name: qbit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=8085
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorren
    volumes:
      - ./config:/config
      - ./Downloads:/downloads
      - ./vuetorrent:/vue
    ports:
      - 8085:8085
    restart: unless-stopped

**Comment by gabe565** [comment]
@ackerthehacker2 Hi! Thanks for opening this. It looks like you might be missing the `t` at the end of your `DOCKER_MODS` string. Can you verify that `DOCKER_MODS` is set to `ghcr.io/gabe565/linuxserver-mod-vuetorrent`?

**Comment by gabe565** [comment]
I just recreated my qBittorrent container to verify the latest version works, and it seems to install fine on my end:
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding gabe565/linuxserver-mod-vuetorrent to container
[mod-init] Downloading gabe565/linuxserver-mod-vuetorrent from ghcr.io
[mod-init] Installing gabe565/linuxserver-mod-vuetorrent
[mod-init] gabe565/linuxserver-mod-vuetorrent applied to container
```
