### ISSUE TITLE
Unacceptable file type, only regular file is allowed.

### ISSUE THREAD

**Issue by daNutzzzzz** [gabe565/linuxserver-mod-vuetorrent#56]
Hi,

Ive had this come up today, nothings changed my end other than linuxserver.io/qbittorrent was updated. If i revert to the previous version of then it works again. 

              > After some troubleshooting, I think this is because the LinuxServer scripts think the mod has already been applied. If you check the Docker logs with `docker compose logs qbittorrent`, which of these do you see?
> 
> 1. ```
>    qbittorrent  | [mod-init] Running Docker Modification Logic
>    qbittorrent  | [mod-init] Adding gabe565/linuxserver-mod-vuetorrent to container
>    qbittorrent  | [mod-init] Downloading gabe565/linuxserver-mod-vuetorrent from ghcr.io
>    qbittorrent  | [mod-init] Installing gabe565/linuxserver-mod-vuetorrent
>    qbittorrent  | [mod-init] gabe565/linuxserver-mod-vuetorrent applied to container
>    ```
> 2. ```
>    qbittorrent  | [mod-init] Running Docker Modification Logic
>    qbittorrent  | [mod-init] Adding gabe565/linuxserver-mod-vuetorrent to container
>    qbittorrent  | [mod-init] gabe565/linuxserver-mod-vuetorrent at 
>    sha256:e13dd95584b75b06ae8e3cf91ca7634056127423d4b2ddb09ac9aeefda02fea0 has been previously applied skipping
>    ```
> 
> If your logs look like number 2 and you don't see the `/vuetorrent` dir inside the container, then I have two ideas that could solve this (see below). I'm not yet sure why the mod wasn't installed during the new version startup.
> 
> To fix, you can either remove the state file and restart:
> 
> 1. `docker compose exec qbittorrent bash`
> 2. `rm /gabe565.linuxserver-mod-vuetorrent.latest`
> 3. `exit`
> 4. `docker compose restart qbittorrent`
> 
> Or you can recreate the container:
> 
> 1. `docker compose rm --stop qbittorrent`
> 2. `docker compose up -d`

Done that, ans now I se this in the container log:

_Originally posted by @glanc in https://github.com/gabe565/linuxserver-mod-vuetorrent/issues/53#issuecomment-2173240721_

**Comment by gabe565** [comment]
@daNutzzzzz I'll reopen and reply to the original issue!
